version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-base
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-cbor
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.module:jackson-module-jaxb-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.apache.solr:solr-test-framework
    versions:
    - 8.7.0
    - 8.8.0
    - 8.8.1
  - dependency-name: org.apache.solr:solr-core
    versions:
    - 8.7.0
    - 8.8.0
    - 8.8.1
  - dependency-name: org.apache.solr:solr-solrj
    versions:
    - 8.7.0
    - 8.8.0
    - 8.8.1
  - dependency-name: com.aliyun.oss:aliyun-sdk-oss
    versions:
    - 3.11.2
    - 3.11.3
  - dependency-name: org.jline:jline
    versions:
    - 3.18.0
  - dependency-name: org.apache.logging.log4j:log4j-core
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.0
